### ISSUE TITLE
Create a site map

### ISSUE THREAD

**Issue by dankolbman** [dankolbman/covid-tested#1]
It will be important to plan out the organization of the website so that we know what pages are categorized where and how the information is organized.

We should create a site map either using a simple text tree or a visual tool like [GlooMaps](https://www.gloomaps.com/) so we can identify the pages that need to be written.

**Comment by chris-s-friedman** [comment]
https://www.gloomaps.com/nviAhAz4lT

**Comment by dankolbman** [comment]
Thanks @chris-s-friedman ! Do you think you can turn these into issues? You could make one issue to write each one of the pages in the site map, for instance.

**Comment by dankolbman** [comment]
Nice! I think we can call this done then.
