### ISSUE TITLE
Establish email contact plan

### ISSUE THREAD

**Issue by dankolbman** [dankolbman/covid-tested#23]
We need to decide how we will be able to provide an email contact for people to reach us at. This includes how we will read and respond to emails which may be difficult as there is a possibility for a high volume of emails.

**Comment by chris-s-friedman** [comment]
[Freshdesk](https://freshdesk.com/pricing) has a free tier and I think many of us already have familiarity with it...

**Comment by chris-s-friedman** [comment]
so maybe freshdesk + a gmail

**Comment by dankolbman** [comment]
We can prioritize this when we start thinking more about outreach.

**Comment by allisonheath** [comment]
We now have hello@getcovidtested.org via G Suite and Freshdesk. G suite might be a bit heavy and we'll have to pay for it in 14 days, but it's what I was familiar with to get us setup quickly with the custom domain.

**Comment by dankolbman** [comment]
Done!
